# ticket_fee: the fee applied to each ticket in a transaction in CENTS. Put down 200 for a $2.00 ticket fee.

---
development:
  ticket_fee: 0
  contact_email: you@example.com
test:
  ticket_fee: 0
  contact_email: you@example.com
production:
  ticket_fee: 0
  contact_email: you@example.com